### ISSUE TITLE
What about dependent tasks?

### ISSUE THREAD

**Issue by rivella50** [alexobviously/secretary#3]
Hi there,

i was about to write my own queueing system and just found your package. Looks very interesting to me.

One question: Can secretary also handle dependency of tasks? 
In my current Flutter mobile app i often have 2 (or more) tasks to process, where the second one can only be performed if the first one was successful. Here an example: The user takes a photo with the camera, and after compressing it the file has to be uploaded to Firebase storage. Only if the upload was successful a new document has to be created in Firestore database with the same id.
So what i need is a way to
- queue the upload and create document Futures
- only create the document if the upload was successful
- retry n times possibility for both the upload and create document task
- retry m times possibility for the whole task (i.e. the task would be started again with the upload if create document failed n times)

Is something like this already possible, and if no, would you be open to implement it?
Thanks a lot for your answer.
Best regards
Valentin

**Comment by alexobviously** [comment]
Hey, this is interesting and I hadn't thought of it like that. When I built this package, I had it in mind that each `Secretary` would be used only for tasks that are similar (i.e. start and end with the same data types) and that's why I put emphasis on strict typing etc.

But anyway, what I currently do with secretary in cases like this is have an instance for each *type* of task, so one for uploads and one for creating the docs. I made a pseudo example for you here: https://github.com/alexobviously/secretary/blob/dev/example/chain.dart.

The only thing from your list that's missing here is "retry m times for the whole task".

I was thinking about maybe making an api that's something like `uploadSec.link(createSec, (file) => createDoc(file));`, that lets you do this without the stream listening part.

Any thoughts?

p.s. I'm away for a few days starting tomorrow so may not reply until I'm back

**Comment by rivella50** [comment]
Wow, i'm impressed. Thanks for reacting so quickly and even provide an example.
Let me check it during the weekend and i will let you know my thoughts.

**Comment by rivella50** [comment]
Linking seems to be an interesting approach, yes.
When thinking about it i came up with two other ideas of how different tasks could be processed in series or in parallel:

- giving up your strict typing policy or allow different task types in a separate way, where the user can choose what he would like to use, i.e. offering him a wider range of possibilities of how tasks can be processed and combined
- some sort of combining secretaries with different task types in a parent secretary, in pseudo code:

```
  final parentSec = GroupSecretary(
    maxAttempts: 5,  // that's the retry m times case
    maxConcurrentTasks: 1,  // this ensures that the secretaries are performed in series
    validator: Validators.resultOk,
  );
  final uploadSec = Secretary<String, Result<StorageFile, int>>(
    maxAttempts: 5,
    maxConcurrentTasks: 3,
    validator: Validators.resultOk,
  );
  final createSec = Secretary<String, Result<FirestoreDoc, int>>(
    maxAttempts: 5,
    maxConcurrentTasks: 3,
    validator: Validators.resultOk,
  );

  parentSec.addChildSecretary(uploadSec);
  parentSec.addChildSecretary(createSec);
```
This would automatically solve the retry m times idea.
What do you think?

**Comment by alexobviously** [comment]
Hey again. So firstly, I published version `0.4.1` which has the `link` function, so try that out and see how you feel about it.

So my feeling about having a separate class like `GroupSecretary` for it is - that is something I also considered but I feel it's creating too much complexity for what is supposed to be quite a streamlined tool. I think it makes more sense in terms of program structure and is easier to visualise, to have independent secretaries that do one sort of thing each. It's also more flexible, since you can `unlink` and restructure the chains this way if you need to, and since in this case (and probably most use cases), ordering is *very* important, I can see drawbacks with a `parent.add` approach (what order are the children in? It's much easier to tell if they are explicitly linked one-way).

`0.4.1` doesn't solve the 'retry the whole thing m times' feature, but I have a vague idea for a container class which tracks the failures and gets passed through each secretary.

But as I was thinking about it I did wonder: what actually is the use case for this? As in: in which situation would you want to retry the entire chain of actions? Surely if you had two actions: 1 - upload file, 2 - create DB record, and part 2 failed more than n times, restarting part 1 wouldn't help if it had already succeeded?

**Comment by rivella50** [comment]
Hi Alex,
cool, this looks good to me and when testing the example apps seems to work fine.
Retry the whole process is probably not needed, yes. And if the 2nd task fails n times then the whole process can just be started manually without having an internal retry option.

So i will test further and see how i can integrate that package into my apps.
Thanks very much for your work - and if i have more ideas i will let you know :-)

**Comment by alexobviously** [comment]
@rivella50 okay cool, I'm going to close this then, let me know if you need anything else :)

**Comment by rivella50** [comment]
Hi Alex,
i have another question - perhaps not directly related to Secretary, but i don't know where to ask elsewhere: How do you personally handle requests which are not initiated by user input, but still need to be performed successfully at some point of time? I.e. you cannot inform the user if such a request fails (n times).

As an example: Let's say the app uses Firebase messaging and therefore from time to time a new messaging token needs to be retrieved from the messaging server and after that stored in the currently logged in Firestore account document.
Both requests do not have to interest the user, they just have to be performed successfully somewhen.

Now with Secretary you can define `maxAttempts` for both requests, but what if the user drives through a tunnel for 30 minutes and those n requests cannot be fulfilled? Does Secretary also offer endless retry option and if yes, would you use it to accomplish it for this scenario - if not how would you solve it?

Possibly not being able to successfully perform those kind of requests is one of the biggest question marks if have when developing mobile apps, and i'm curious what you think about it.

Thanks a lot for your answer.
Best regards
Valentin
